spring :
  application :
    name: auth-server
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8090
  servlet:
    context-path: /svc/auth
jwt:
  secret: Xv1qj8+0Vd6k2ZGk7RkB0TzJ4GqWJXVy9DfV4bNvl6Y=
